[workspace]
members = [
    "boreal-parser",
    "boreal",
    "boreal-cli",
]

[patch.crates-io]
# Fork of object crate, for additional features, but also hacks that probably cannot
# be pushed upstreamed, but are required to align with yara's behavior
#
# - Support for delay load table:
#   - 6f6794a46bcbf1f709dcd7e8693b79aa7b8505e0
#   - 4f986f227998660ce26ccfc459b3410a450622cd
# - Handling of FileAlignment on section's offset to raw data:
#   - 57e46356d674420c628be876ac488170f5867aa1
#   - a5be655e9a7d662d485de3240f6dcdf1f0e92499
# - Retrieval of raw name for sections
#   - b28e4e82dc8979225ca8c483c49ea2e127795db7
# - Retrieval of raw data for resource names
#   - https://github.com/gimli-rs/object/pull/487
object = { git = 'https://github.com/vthib/boreal-object', branch = "version-0.29" }
