[workspace]
members = [
    "boreal-parser",
    "boreal",
    "boreal-cli",
]

[patch.crates-io]
# Fork of object crate, for additional features, but also hacks that probably cannot
# be pushed upstreamed, but are required to align with yara's behavior
#
# - Handling of FileAlignment on section's offset to raw data:
#   - 2004ec0adb8c2e5d7de09dfcd5e4c80c14cae296
#   - 7b7257d768b09a2664cbab2a46a0c37779c91d9c
# - Retrieval of raw name for sections
#   - f9caed56c480f8e3c5e1f971cab76ad0a1ccae5a
object = { git = 'https://github.com/vthib/boreal-object', branch = "version-0.30" }
