[package]
name = "boreal-cli"
version = "0.0.1"
description = "CLI utility to run boreal, a YARA rules engine"
repository = "https://github.com/vthib/boreal"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["boreal", "yara", "string-matching", "scan"]
categories = ["command-line-utilities", "text-processing"]
edition = "2021"

[[bin]]
name = "boreal"
path = "src/main.rs"

[dependencies]
boreal = { path = "../boreal", version = "0.0.1" }

# CLI arguments handling
clap = { version = "4.0", features = ["derive"] }

# Proper error reporting on parsing
codespan-reporting = "0.11"

# Parallel evaluation on scanned directories
crossbeam-channel = "0.5"

# Display of bytes values
hex = "0.4"

# Walking through directories
walkdir = "2.3"
