[package]
name = "boreal-cli"
version = "0.0.1"
repository = "https://github.com/vthib/boreal"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "boreal"
path = "src/main.rs"

[dependencies]
boreal = { path = "../boreal", version = "0.0.1" }

# CLI arguments handling
clap = { version = "4.0", features = ["derive"] }

# Proper error reporting on parsing
codespan-reporting = "0.11"

# Display of bytes values
hex = "0.4"

# Walking through directories
walkdir = "2.3"
