[package]
name = "boreal"
version = "0.0.1"
repository = "https://github.com/vthib/boreal"
edition = "2021"

[dependencies]
boreal-parser = { path = "../boreal-parser" }

regex = "1.5"

# Proper error reporting on parsing
codespan-reporting = "0.11"

# Scanning for bytes
grep-matcher = "0.1"
grep-regex = "0.1"
