[package]
name = "boreal"
version = "0.0.1"
repository = "https://github.com/vthib/boreal"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
boreal-parser = { path = "../boreal-parser", version = "0.0.1" }

regex = "1.5"
# Needed to parse & modify HIR for some modifiers (eg wide regex)
# No default features to disable unicode, we do not need it
regex-syntax = { version = "0.6", default-features = false }

# Proper error reporting on compilation
codespan-reporting = "0.11"

# Scanning for bytes
grep-matcher = "0.1"
grep-regex = "0.1"
aho-corasick = "0.7"

[dev-dependencies]
const_format = "0.2"
yara = { version = "0.13", features = ["vendored"] }
base64 = "0.13"
