name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '45 4 * * 3'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test ${{matrix.build}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{matrix.target}}
      - run: cargo test
      - name: Test with Openssl
        if: ${{ matrix.os != 'windows-latest' }}
        run: cargo test --features openssl

    strategy:
      fail-fast: false
      matrix:
        build: [linux, linux32, windows, windows32]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux32
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: windows32
            os: windows-latest
            target: i686-pc-windows-msvc

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --tests --all-features

  rustmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
